# https://www.playframework.com/documentation/latest/Configuration
db.default.driver=org.postgresql.Driver
db.default.url="jdbc:postgresql://localhost:5432/pulse"
db.default.username=${?DB_USER}
db.default.password=${?DB_PASSWORD}

slick.dbs.default.profile="slick.jdbc.PostgresProfile$"
slick.dbs.default.db.driver="org.postgresql.Driver"
slick.dbs.default.db.url="jdbc:postgresql://localhost:5432/pulse"
slick.dbs.default.db.user=${?DB_USER}
slick.dbs.default.db.password=${?DB_PASSWORD}

play.evolutions.enabled=true
play.evolutions.autoApply=true

play.filters.disabled += "play.filters.csrf.CSRFFilter"

jwt {
secret = "default-dev-key-change-this-in-production-12345"
secret = ${?SECRET_KEY}
issuer = "pulse-app-api"
expiry-seconds = 3600
}