# https://www.playframework.com/documentation/latest/Configuration
db.default.driver=org.postgresql.Driver
; db.default.url="jdbc:postgresql://localhost:5432/pulse"
db.default.url=${?DB_URL}
db.default.username=${?DB_USER}
db.default.password=${?DB_PASSWORD}

slick.dbs.default.profile="slick.jdbc.PostgresProfile$"
slick.dbs.default.db.driver="org.postgresql.Driver"
; slick.dbs.default.db.url="jdbc:postgresql://localhost:5432/pulse"
slick.dbs.default.db.url=${?SLICK_URL}
slick.dbs.default.db.user=${?DB_USER}
slick.dbs.default.db.password=${?DB_PASSWORD}
gemini {
api-key = ${GEMINI_API_KEY}
base-url = "https://generativelanguage.googleapis.com/v1beta"
base-url-local = "http://localhost:11434/api"
extraction-model = "qwen3:4b"
; extraction-model = "gemini-2.5-flash"
embedding-model = "gemini-embedding-001"
max-retries = 3
retry-base-delay-ms = 1000
requests-per-minute = 9
}

qdrant {
host = "localhost"
host = ${?QDRANT_HOST}
port = 6334
port = ${?QDRANT_PORT}
collection-name = "pulse_appreciations"
award-definitions-collection-name = "pulse_award_definitions"
vector-dimensions = 3072
}
play.evolutions.enabled=true
play.evolutions.autoApply=true

play.filters.disabled += "play.filters.csrf.CSRFFilter"

jwt {
; secret = "default-dev-key-change-this-in-production-12345"
secret = ${?SECRET_KEY}
issuer = "pulse-app-api"
expiry-seconds = 3600
}